### ISSUE TITLE
seem to be missing material on the ServiceNow Admin Zero to Hero

### ISSUE THREAD

**Issue by kdelbridge** [PacktPublishing/ServiceNow-System-Administrator-from-Zero-to-Hero#1]
- I was able to launch the courseware, but my concern is that all the documents that are available do not seem to be all the documents. there is mention of a video on the book page and assignment docs keep referring to "more info on the lecture" and I don't have any of that.

- I have an assignments document that starts with Assignment 3, and trying to find out....where are assignments 1 & 2?

- Where's the lecture and video mentioned?
- what I have is a bunch of micro steps on assignment docs, but NO context at all and certainly NOT course material
screenshot shows what I have right now
![Capture](https://github.com/PacktPublishing/ServiceNow-System-Administrator-from-Zero-to-Hero/assets/136755818/499370ed-7d0d-4808-b231-e5c5cb95f4ef)

**Comment by Sonakshis** [comment]
Hi,
The assignments listed under the heading do not follow a sequential numbering system. They are marked as "Section 3 assignment," indicating that they are not the third assignment but rather the assignment for section 3. Please keep in mind that parts 1 and 2 don't have any assignments. 
You had previously informed us that you purchased the course via VitalSource Bookshelf. Once you have purchased the course, please follow the following steps as listed on the website (here is a screenshot for your reference): 
https://www.vitalsource.com/products/servicenow-system-administrator-from-zero-to-hero-catalin-popa-v9781803243092 

<img width="717" alt="MicrosoftTeams-image (1)" src="https://github.com/PacktPublishing/ServiceNow-System-Administrator-from-Zero-to-Hero/assets/85751562/80f4eef5-14f5-47bb-8809-95cc4719e9d0">

You can access the full course here:  

https://www.packtpub.com/product/servicenow-system-administrator-from-zero-to-hero-video/9781803243092#_ga=2.177989541.1661732994.1687334705-1783352676.1681914805
